management.context-path=/sysinfo
server.port=8080
spring.security.user.name=wd
spring.security.user.password=wd
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost/data
spring.datasource.username=pma
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect